# Generated by Django 4.1.4 on 2024-09-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('dv', 'Spanish')], max_length=50),
        ),
    ]
