# Generated by Django 4.1.4 on 2024-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('teams', models.CharField(max_length=200)),
                ('achievement', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(max_length=200)),
                ('ratio', models.CharField(max_length=200)),
                ('assists', models.CharField(max_length=200)),
                ('matches', models.CharField(max_length=200)),
                ('titles', models.CharField(max_length=200)),
                ('awards', models.CharField(max_length=200)),
            ],
        ),
    ]
